source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Player' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Player
  pod 'MBProgressHUD'
  pod 'MarqueeLabel'
  pod 'XCGLogger', '~> 4.0.0'

  target 'PlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

